### ISSUE TITLE
docker support for pool protocal

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-docker#91] opened 2021-07-01 12:28 UTC
how to join a pool by this

**Comment by Yamanipanuchi** [comment] 2021-07-09 17:15
You cannot join to pool using the docker yet, As it has not been updated.

**Comment by justinrush** [comment] 2021-07-12 13:22
The latest tag is being built for 1.2.1-dev0 - it looks like they build it off master on some regular basis.

I was trying to modify the dockerfile to build on the tag, but even though this works when running the commands outside of a docker build, the resulting `chia version` command still shows 1.2.1-dev0 when building with docker. Any clue why that is?

```dockerfile
FROM ubuntu:focal as builder

EXPOSE 8555
EXPOSE 8444

ENV keys="generate"
ENV harvester="false"
ENV farmer="false"
ENV clionly="false"
ENV plots_dir="/plots"
ENV farmer_address="null"
ENV farmer_port="null"
ENV testnet="false"
ENV full_node_port="null"
ENV TZ="UTC"
ARG TAG="1.2.0"

# hadolint ignore=DL3008
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl jq python3 \
        ansible tar bash ca-certificates git openssl unzip wget python3-pip sudo acl \
        build-essential python3-dev python3.8-venv python3.8-distutils apt nfs-common \
        python-is-python3 vim tzdata lsb-release bc && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN echo "cloning ${TAG}"

WORKDIR /chia-blockchain
RUN git clone --branch ${TAG} https://github.com/Chia-Network/chia-blockchain.git . && \
    chmod +x install.sh && \
    /usr/bin/sh ./install.sh

WORKDIR /chia-blockchain

ENV PATH=/chia-blockchain/venv/bin/:$PATH
COPY ./entrypoint.sh entrypoint.sh

ENTRYPOINT ["bash", "./entrypoint.sh"]

```

**Comment by sd016808** [comment] 2021-08-17 14:50
I use the 

> The latest tag is being built for 1.2.1-dev0 - it looks like they build it off master on some regular basis.
> 
> I was trying to modify the dockerfile to build on the tag, but even though this works when running the commands outside of a docker build, the resulting `chia version` command still shows 1.2.1-dev0 when building with docker. Any clue why that is?
> 
> ```dockerfile
> FROM ubuntu:focal as builder
> 
> EXPOSE 8555
> EXPOSE 8444
> 
> ENV keys="generate"
> ENV harvester="false"
> ENV farmer="false"
> ENV clionly="false"
> ENV plots_dir="/plots"
> ENV farmer_address="null"
> ENV farmer_port="null"
> ENV testnet="false"
> ENV full_node_port="null"
> ENV TZ="UTC"
> ARG TAG="1.2.0"
> 
> # hadolint ignore=DL3008
> RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
>     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl jq python3 \
>         ansible tar bash ca-certificates git openssl unzip wget python3-pip sudo acl \
>         build-essential python3-dev python3.8-venv python3.8-distutils apt nfs-common \
>         python-is-python3 vim tzdata lsb-release bc && \
>         apt-get clean && \
>         rm -rf /var/lib/apt/lists/*
> 
> RUN echo "cloning ${TAG}"
> 
> WORKDIR /chia-blockchain
> RUN git clone --branch ${TAG} https://github.com/Chia-Network/chia-blockchain.git . && \
>     chmod +x install.sh && \
>     /usr/bin/sh ./install.sh
> 
> WORKDIR /chia-blockchain
> 
> ENV PATH=/chia-blockchain/venv/bin/:$PATH
> COPY ./entrypoint.sh entrypoint.sh
> 
> ENTRYPOINT ["bash", "./entrypoint.sh"]
> ```

I use this dockerfile with the TAG="1.2.3". 
The chia version shows 1.2.4.dev0 inside the container.
I can see the Farming Status is farming as below:
![image](https://user-images.githubusercontent.com/9477727/129748085-7de0aede-e4de-4a72-9151-907be2f82049.png)

But the space pool can not receive and contribute by me as below:
![image](https://user-images.githubusercontent.com/9477727/129748345-2b18c802-1c35-460b-8f3f-7aaa62595b70.png)

Before I use the GUI version everything works fine. 
I upload the debug.log file, can anyone help me to check why the space pool receive and contribute by me?
[debug.log](https://github.com/Chia-Network/chia-docker/files/7000933/debug.log)

**Comment by sd016808** [comment] 2021-08-18 03:41
I use the remote GUI to see what happened.
I found the pool page is empty. Then I randomly join a pool.
After the joined, the pool page reloads and shows my pools back.
Everything works fine now.

**Comment by Motophan** [comment] 2021-08-23 06:47
Can we get this added?

**Comment by Motophan** [comment] 2021-08-24 06:45
@justinrush
Can you make a PR and / or upload your container to the hub? 
I cant pull a container on synology unless it is in the hub

**Comment by ukewea** [comment] 2021-08-24 07:38
> I cant pull a container on synology unless it is in the hub

@Motophan I pushed a image with 1.2.3 on [Docker Hub](https://hub.docker.com/r/wuuker/chia-docker), can you try it and report the result?

**Comment by justinrush** [comment] 2021-09-08 16:28
if a maintainer on this project exists and responds that they'd be open to it, i'd be open to doing a pull request

**Comment by Motophan** [comment] 2021-09-11 02:54
bump

**Comment by cmmarslender** [comment] 2021-09-16 16:49
Can someone summarize the current issues here, if there are any? the .dev0 version issue in the container (was only cosmetic) should be resolved. The image on dockerhub has both `latest` tags and tags based on versions of chia-blockchain (1.2.6, etc) - the `latest` container always points to the most recent release of chia-blockchain. I'm not sure what would be preventing pooling from working, since these containers do have the latest version of chia-blockchain available.

**Comment by ukewea** [comment] 2021-09-17 04:56
The image had not been update for a period of time when this issue is filed, joining official pool is not possible with the latest official image at that time (the latest version by then is probably 1.2.0 or older).

But the issue is gone now since the [official image](https://hub.docker.com/r/chianetwork/chia-docker) is catching up with latest Chia release.

**Comment by cmmarslender** [comment] 2021-09-17 16:23
Got it. I was just confused by the recent "bump" on this thread, since we've been automatically building a new `latest` tag for longer than 7 days. Either way, I'll go ahead and close this, as latest is always the latest blockchain release, and we also have version tags now (1.2.6, etc). If there is still an issue with pooling on the latest images, please comment and reopen here with the specific problems :)

**Closed by cmmarslender** 2021-09-17 16:23 UTC
